name: 'Test Engineer Agent'
description: 'Run tests and enforce coverage'

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.11'
  coverage-threshold:
    description: 'Minimum coverage percentage'
    required: false
    default: '80'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: 'latest'

    - name: Run tests with coverage
      shell: bash
      run: |
        pixi run pytest \
          --cov=src \
          --cov-report=term \
          --cov-report=xml \
          --cov-report=html \
          --cov-fail-under=${{ inputs.coverage-threshold }}

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: always()
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

    - name: Check for skipped tests
      shell: bash
      run: |
        if pixi run pytest --collect-only -q | grep -q "skipped"; then
          echo "Error: Skipped tests found. Fix or remove them."
          exit 1
        fi
