name: 'Code Review Agent'
description: 'Enforce code quality standards'

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: 'latest'

    - name: Run ruff format check
      shell: bash
      run: pixi run ruff format --check .

    - name: Run ruff lint
      shell: bash
      run: pixi run ruff check .

    - name: Run mypy
      shell: bash
      run: pixi run mypy src/

    - name: Check import sorting
      shell: bash
      run: pixi run ruff check --select I .

    - name: Security checks
      shell: bash
      run: pixi run ruff check --select S .
